# Generated by Django 2.2.4 on 2020-02-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=5000)),
                ('numbers', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': '电视剧集数',
            },
        ),
    ]
