# Generated by Django 2.2.4 on 2020-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_detailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmodel',
            name='name',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
